name = "messengr-backend"
zone_id = ""
account_id = ""
route = ""
workers_dev=true
compatibility_date = "2022-08-25"
type="javascript"

[build]
command = "yarn && yarn build"

[build.upload]
main = "./index.mjs"
format = "modules"

[durable_objects]
bindings = [
    {name = "STORAGE", class_name = "StorageDO"}
]

[[migrations]]
tag = "v1"
new_classes = ["StorageDO"]

